# Generated by Django 3.2.9 on 2021-12-02 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='featured',
            field=models.BooleanField(default=False),
        ),
    ]
