# Generated by Django 3.2.9 on 2021-12-01 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='CategoryCourse',
        ),
        migrations.AddField(
            model_name='course',
            name='categories',
            field=models.ManyToManyField(to='blog.CategoryCourse'),
        ),
        migrations.AddField(
            model_name='course',
            name='image',
            field=models.ImageField(default=-5, upload_to='image-course/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(to='blog.CategoryPost'),
        ),
    ]
